#!/usr/bin/env python3
"""Generate an LCSC BOM audit for the rover-circuit KiCad project.

This script is intentionally project-local analysis output. It reads the BOM
JSON generated by the BOM skill, queries the public jlcsearch/LCSC APIs, and
emits a CSV, Markdown report, and a conservative KiCad property update JSON.
"""

from __future__ import annotations

import csv
import importlib.util
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "analysis"
BASELINE = Path("/tmp/rover_bom_baseline.json")
LCSC_FETCH = Path("/home/nicolas/.codex/skills/lcsc/scripts/fetch_datasheet_lcsc.py")
USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
BUILD_QTY = 5


spec = importlib.util.spec_from_file_location("fetch_datasheet_lcsc", LCSC_FETCH)
if spec is None or spec.loader is None:
    raise SystemExit(f"Cannot import {LCSC_FETCH}")
lcsc_mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(lcsc_mod)


def normalize_code(value: str) -> str:
    value = (value or "").strip().upper()
    if re.match(r"^C\d+$", value):
        return value
    return ""


def parse_extra(component: dict[str, Any]) -> dict[str, Any]:
    return lcsc_mod._parse_extra(component)


def get_number(component: dict[str, Any]) -> str:
    return lcsc_mod._get_lcsc_code(component)


def get_mpn(component: dict[str, Any]) -> str:
    return lcsc_mod._get_mpn(component)


def get_manufacturer(component: dict[str, Any]) -> str:
    mfg = lcsc_mod._get_manufacturer(component)
    if mfg:
        return mfg
    mpn = get_mpn(component).upper()
    fallbacks = {
        "MMC5983MA": "MEMSIC",
        "BMI270": "Bosch Sensortec",
        "DWM1000": "Qorvo",
    }
    return fallbacks.get(mpn, "")


def get_description(component: dict[str, Any]) -> str:
    return lcsc_mod._get_description(component)


def get_datasheet(component: dict[str, Any] | None) -> str:
    if not component:
        return ""
    return lcsc_mod._get_datasheet_url(component)


def api_search(query: str, limit: int = 20) -> list[dict[str, Any]]:
    url = (
        "https://jlcsearch.tscircuit.com/api/search?"
        + urllib.parse.urlencode({"q": query, "limit": limit, "full": "true"})
    )
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=20) as resp:
        data = json.loads(resp.read())
    out = data.get("components", [])
    for component in out:
        parse_extra(component)
    return out


def component_by_code(code: str) -> dict[str, Any] | None:
    code = normalize_code(code)
    if not code:
        return None
    component = lcsc_mod.search_lcsc(code) or lcsc_mod.search_lcsc_direct(code)
    if component:
        parse_extra(component)
    return component


def stock(component: dict[str, Any] | None) -> int:
    if not component:
        return 0
    extra = component.get("extra") or {}
    return int(extra.get("quantity") or component.get("stock") or 0)


def price_breaks(component: dict[str, Any] | None) -> list[dict[str, Any]]:
    if not component:
        return []
    extra = component.get("extra") or {}
    prices = extra.get("prices") or component.get("price") or []
    if not isinstance(prices, list):
        return []
    return prices


def unit_price(component: dict[str, Any] | None, qty: int) -> float | None:
    prices = price_breaks(component)
    best = None
    for row in prices:
        q_from = int(row.get("min_qty") or row.get("qFrom") or 1)
        q_to_raw = row.get("max_qty") or row.get("qTo") or 10**12
        q_to = int(q_to_raw) if q_to_raw not in ("", None) else 10**12
        price_raw = row.get("price")
        if price_raw is None:
            continue
        price = float(price_raw)
        if q_from <= qty <= q_to:
            return price
        if q_from <= qty and (best is None or q_from > best[0]):
            best = (q_from, price)
    if best:
        return best[1]
    if prices:
        try:
            return float(prices[0].get("price"))
        except (TypeError, ValueError):
            return None
    top = component.get("price") if component else None
    return float(top) if isinstance(top, (int, float)) else None


def moq(component: dict[str, Any] | None) -> int:
    extra = component.get("extra") if component else {}
    if not isinstance(extra, dict):
        return 1
    return int(extra.get("moq") or 1)


def multiple(component: dict[str, Any] | None) -> int:
    extra = component.get("extra") if component else {}
    if not isinstance(extra, dict):
        return 1
    return int(extra.get("order_multiple") or 1)


def buy_qty(required: int, component: dict[str, Any] | None) -> int:
    min_qty = moq(component)
    mult = max(1, multiple(component))
    qty = max(required, min_qty)
    if qty % mult:
        qty += mult - qty % mult
    return qty


def basic(component: dict[str, Any] | None) -> str:
    if not component:
        return ""
    return "basic" if int(component.get("basic") or 0) else "extended"


def package(component: dict[str, Any] | None) -> str:
    if not component:
        return ""
    extra = component.get("extra") or {}
    return str(extra.get("package") or component.get("package") or "")


def attributes(component: dict[str, Any] | None) -> dict[str, Any]:
    if not component:
        return {}
    extra = component.get("extra") or {}
    attrs = extra.get("attributes") or {}
    return attrs if isinstance(attrs, dict) else {}


def money(value: float | None) -> str:
    if value is None:
        return ""
    return f"{value:.6f}"


def compact(text: str, limit: int = 96) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    return text if len(text) <= limit else text[: limit - 1] + "..."


def footprint_package(footprint: str) -> str:
    m = re.search(r"([CRL])_(\d{4})_", footprint)
    if m:
        return m.group(2)
    if "LED_0603" in footprint:
        return "0603"
    if "0402" in footprint:
        return "0402"
    if "0603" in footprint:
        return "0603"
    if "0805" in footprint:
        return "0805"
    if "1206" in footprint:
        return "1206"
    if "2512" in footprint:
        return "2512"
    return ""


def package_ok(expected: str, actual: str) -> bool:
    if not expected:
        return True
    return expected.lower() in actual.lower().replace("-", "")


def value_token(value: str) -> str:
    return value.replace("Ω", "").replace(" ", "").lower()


def validate_line(line: dict[str, Any], component: dict[str, Any] | None) -> tuple[str, str]:
    if line.get("type") == "test_point":
        return "n/a", "PCB test pad; no purchased LCSC component required"
    if not line.get("lcsc"):
        return "missing", "No LCSC code in schematic"
    if not component:
        return "fail", "LCSC code did not resolve"
    expected_pkg = footprint_package(line.get("footprint", ""))
    actual_pkg = package(component)
    if not package_ok(expected_pkg, actual_pkg):
        return "review", f"Package check needs review: footprint {expected_pkg}, LCSC {actual_pkg}"
    desc = get_description(component)
    attrs = attributes(component)
    line_type = line.get("type")
    if stock(component) <= 0:
        return "review", "No current LCSC stock reported"
    live_mpn = get_mpn(component).upper()
    schematic_mpn = (line.get("mpn") or "").upper()
    if schematic_mpn and live_mpn == schematic_mpn:
        return "ok", "Exact LCSC code resolves to schematic MPN with matching package and stock"
    val = value_token(line.get("value", ""))
    haystack = value_token(" ".join([desc, json.dumps(attrs, sort_keys=True)]))
    if line_type in {"resistor", "capacitor", "inductor"} and val and val not in haystack:
        aliases = {
            "100n": ["100nf", "0.1uf"],
            "0.1uf": ["100nf", "100n"],
            "200m": ["0.2", "200m", "0r2"],
            "10": ["10r", "10ohm"],
            "300": ["300r", "300ohm"],
            "470": ["470r", "470ohm"],
        }.get(val, [])
        if not any(alias in haystack for alias in aliases):
            return "review", "Value not obvious in LCSC attributes/description"
    return "ok", "Package/value/stock checks pass from LCSC metadata"


@dataclass
class Candidate:
    ref: str
    action: str
    manufacturer: str
    mpn: str
    lcsc: str
    datasheet: str
    note: str


def find_exact_candidate(query: str, require_pkg: str = "") -> dict[str, Any] | None:
    results = api_search(query, limit=20)
    for component in results:
        if require_pkg and not package_ok(require_pkg, package(component)):
            continue
        if stock(component) <= 0:
            continue
        return component
    return results[0] if results else None


def candidate_for_missing(line: dict[str, Any], existing_by_key: dict[tuple[str, str], dict[str, Any]]) -> Candidate | None:
    refs = ",".join(line["references"])
    value = line["value"]
    footprint = line.get("footprint", "")
    expected_pkg = footprint_package(footprint)

    # Reuse already validated equivalent commodity choices from the schematic.
    reuse = existing_by_key.get((value.lower(), footprint))
    if reuse:
        return Candidate(
            ref=refs,
            action="fill",
            manufacturer=reuse.get("manufacturer", ""),
            mpn=reuse.get("mpn", ""),
            lcsc=reuse.get("lcsc", ""),
            datasheet=reuse.get("datasheet", ""),
            note="Reuse existing same value/footprint BOM line",
        )

    queries = {
        "U1": "MMC5983MA",
        "U11": "BMI270",
        "DWM1": "DWM1000",
    }
    first_ref = line["references"][0]
    query = queries.get(first_ref)
    if first_ref in {"J7", "J8"}:
        query = "S2B-PH-SM4-TB"
    elif first_ref == "J9":
        query = "S4B-PH-SM4-TB"
    elif query is None and value.startswith("MCP1799"):
        query = "MCP1799 500 SOT-23"
    elif query is None and value.startswith("STM6601"):
        query = "STM6601 TDFN-12"
    elif query is None and first_ref == "J3":
        return Candidate(ref=refs, action="manual", manufacturer="", mpn="", lcsc="", datasheet="", note="Missing footprint; cannot safely select connector")
    elif query is None:
        return None

    try:
        component = find_exact_candidate(query, expected_pkg)
        time.sleep(0.5)
    except Exception as exc:
        return Candidate(ref=refs, action="manual", manufacturer="", mpn="", lcsc="", datasheet="", note=f"LCSC search failed: {exc}")
    if not component:
        return Candidate(ref=refs, action="manual", manufacturer="", mpn="", lcsc="", datasheet="", note=f"No LCSC result for {query}")
    return Candidate(
        ref=refs,
        action="review" if first_ref in {"U8", "U12", "J7", "J8", "J9"} else "fill",
        manufacturer=get_manufacturer(component),
        mpn=get_mpn(component),
        lcsc=get_number(component),
        datasheet=get_datasheet(component),
        note=f"Best live LCSC result for query '{query}'; review required unless exact package/variant is confirmed",
    )


def main() -> int:
    baseline = json.loads(BASELINE.read_text())
    bom = [line for line in baseline["bom"] if not line.get("dnp")]

    cache: dict[str, dict[str, Any] | None] = {}
    rows: list[dict[str, Any]] = []
    existing_by_key: dict[tuple[str, str], dict[str, Any]] = {}

    for line in bom:
        if line.get("mpn") and line.get("lcsc"):
            existing_by_key.setdefault((line["value"].lower(), line.get("footprint", "")), line)

    for line in bom:
        code = normalize_code(line.get("lcsc", ""))
        component = None
        if code:
            if code not in cache:
                cache[code] = component_by_code(code)
                time.sleep(0.5)
            component = cache[code]
        required = line["quantity"] * BUILD_QTY
        bq = buy_qty(required, component) if component else required
        up = unit_price(component, bq) if component else None
        status, note = validate_line(line, component)
        rows.append(
            {
                "references": ",".join(line["references"]),
                "qty_per_board": line["quantity"],
                "required_for_5_boards": required,
                "value": line["value"],
                "type": line["type"],
                "footprint": line.get("footprint", ""),
                "schematic_manufacturer": line.get("manufacturer", ""),
                "schematic_mpn": line.get("mpn", ""),
                "schematic_lcsc": line.get("lcsc", ""),
                "live_manufacturer": get_manufacturer(component) if component else "",
                "live_mpn": get_mpn(component) if component else "",
                "live_lcsc": get_number(component) if component else "",
                "live_package": package(component),
                "basic_extended": basic(component),
                "stock": stock(component),
                "moq": moq(component) if component else "",
                "multiple": multiple(component) if component else "",
                "buy_qty": bq if component else "",
                "unit_price_usd": money(up),
                "extended_price_usd": money((up or 0) * bq if up is not None else None),
                "datasheet": get_datasheet(component) or line.get("datasheet", ""),
                "validation": status,
                "notes": note,
                "description": compact(get_description(component) if component else line.get("description", "")),
            }
        )

    missing = [
        line for line in bom
        if "mpn" in line.get("gaps", []) or "lcsc" in line.get("gaps", [])
    ]
    candidates: list[Candidate] = []
    for line in missing:
        cand = candidate_for_missing(line, existing_by_key)
        if cand:
            candidates.append(cand)

    updates: dict[str, dict[str, str]] = {}
    # Only auto-apply conservative commodity/same-footprint reuses and exact
    # high-confidence sensor/module fills. Connectors/regulator variants stay review.
    auto_refs = {"C32", "U1", "U11"}
    for cand in candidates:
        ref_list = cand.ref.split(",")
        if cand.action == "fill" and all(ref in auto_refs for ref in ref_list) and cand.lcsc:
            for ref in ref_list:
                updates[ref] = {
                    "Manufacturer": cand.manufacturer,
                    "MPN": cand.mpn,
                    "LCSC": cand.lcsc,
                }
                if cand.datasheet:
                    updates[ref]["Datasheet"] = cand.datasheet

    csv_path = OUT_DIR / "lcsc_bom_audit_2026-05-22.csv"
    md_path = OUT_DIR / "lcsc_bom_audit_2026-05-22.md"
    updates_path = OUT_DIR / "lcsc_bom_updates_2026-05-22.json"

    with csv_path.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    total = sum(float(row["extended_price_usd"] or 0) for row in rows)
    ok = sum(1 for row in rows if row["validation"] == "ok")
    review = sum(1 for row in rows if row["validation"] == "review")
    missing_count = sum(1 for row in rows if row["validation"] == "missing")
    fail = sum(1 for row in rows if row["validation"] == "fail")

    lines = [
        "# LCSC BOM audit - 2026-05-22",
        "",
        f"Target build quantity: {BUILD_QTY} boards.",
        f"Estimated LCSC component spend from resolvable current selections: ${total:.2f}.",
        f"Validation counts: {ok} ok, {review} review, {missing_count} missing, {fail} fail.",
        "",
        "## Conservative updates generated",
        "",
    ]
    if updates:
        for ref, props in sorted(updates.items()):
            lines.append(f"- {ref}: {props.get('Manufacturer')} {props.get('MPN')} / {props.get('LCSC')}")
    else:
        lines.append("- None.")
    lines.extend(["", "## Missing-part candidates", ""])
    for cand in candidates:
        fields = [cand.ref, cand.action, cand.manufacturer, cand.mpn, cand.lcsc, cand.note]
        lines.append("- " + " | ".join(str(f) for f in fields if f))
    lines.extend(["", "## Lines needing manual review", ""])
    for row in rows:
        if row["validation"] in {"review", "missing", "fail"}:
            lines.append(
                f"- {row['references']}: {row['value']} {row['footprint']} / "
                f"{row['schematic_lcsc'] or 'no LCSC'} - {row['validation']}: {row['notes']}"
            )
    lines.extend(["", "## Full table", ""])
    lines.append("| Refs | Value | Footprint | LCSC | Live MPN | Package | Stock | Buy qty | Unit USD | Status | Notes |")
    lines.append("|---|---|---|---|---|---|---:|---:|---:|---|---|")
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    row["references"],
                    row["value"],
                    row["footprint"],
                    row["schematic_lcsc"],
                    row["live_mpn"],
                    row["live_package"],
                    str(row["stock"]),
                    str(row["buy_qty"]),
                    row["unit_price_usd"],
                    row["validation"],
                    row["notes"],
                ]
            )
            + " |"
        )
    md_path.write_text("\n".join(lines) + "\n")
    updates_path.write_text(json.dumps(updates, indent=2, sort_keys=True) + "\n")

    print(json.dumps({
        "csv": str(csv_path),
        "markdown": str(md_path),
        "updates": str(updates_path),
        "estimated_total_usd": round(total, 4),
        "validation": {"ok": ok, "review": review, "missing": missing_count, "fail": fail},
        "generated_updates": updates,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
